Repository fatenchtay98/train-me-ai, pull requests merged in 2025-04, with the labels that each got.

#2 Initial setup for EEP with streamlit structure, pages, and core modules
  EEP/.env
  EEP/.streamlit/config.toml
  EEP/Dockerfile
  EEP/app.py
  EEP/core/config.py
  EEP/core/database.py
  EEP/core/db_utils.py
  EEP/core/models.py
  EEP/pages/About.py
  EEP/pages/Dashboard.py
  EEP/pages/DietRecommender.py
  EEP/pages/Home.py
  EEP/pages/Login.py
  EEP/pages/PoseEstimation.py
  EEP/pages/SignUp.py
  EEP/pages/WorkoutRecommender.py
  EEP/requirements.txt
  EEP/sidebar.py
  EEP/static/icons/dumbbell.svg
  EEP/static/icons/home.svg
  EEP/static/icons/info.svg
  EEP/static/icons/layout-dashboard.svg
  EEP/static/icons/log-in.svg
  EEP/static/icons/logo.png
  EEP/static/icons/salad.svg
  EEP/static/icons/switch-camera.svg
  EEP/static/icons/user-plus.svg
  docker-compose.yml
Labels: feature, frontend

#17 feat: add IEP2 - Workout Recommendation API with PPO RL and feedback logic
  IEP2/.env
  IEP2/Dockerfile
  IEP2/app/__init__.py
  IEP2/app/api/v1/__init__.py
  IEP2/app/api/v1/__pycache__/__init__.cpython-38.pyc
  IEP2/app/api/v1/__pycache__/endpoints.cpython-38.pyc
  IEP2/app/api/v1/__pycache__/schemas.cpython-38.pyc
  IEP2/app/api/v1/endpoints.py
  IEP2/app/api/v1/schemas.py
  IEP2/app/core/__pycache__/config.cpython-38.pyc
  IEP2/app/core/config.py
  IEP2/app/data/__pycache__/exercises.cpython-38.pyc
  IEP2/app/data/exercises.py
  IEP2/app/db/__init__.py
  IEP2/app/db/__pycache__/__init__.cpython-38.pyc
  IEP2/app/db/__pycache__/database.cpython-38.pyc
  IEP2/app/db/__pycache__/models.cpython-38.pyc
  IEP2/app/db/database.py
  IEP2/app/db/models.py
  IEP2/app/main.py
  IEP2/app/rl/__init__.py
  IEP2/app/rl/envs/env.py
  IEP2/app/rl/envs/env_feedback.py
  IEP2/models/legs/ppo_legs_model_20250419_1725.zip
  IEP2/models/legs/ppo_legs_model_20250419_1726.zip
  IEP2/models/legs/ppo_legs_model_latest.zip
  IEP2/models/legs/reward_curve_20250419_1721.png
  IEP2/models/legs/reward_curve_20250419_1723.png
  IEP2/models/legs/reward_curve_20250419_1725.png
  IEP2/models/legs/reward_curve_20250419_1726.png
  IEP2/models/pull/ppo_pull_model_20250419_1725.zip
  IEP2/models/pull/ppo_pull_model_20250419_1726.zip
  IEP2/models/pull/ppo_pull_model_latest.zip
  IEP2/models/pull/reward_curve_20250419_1720.png
  IEP2/models/pull/reward_curve_20250419_1723.png
  IEP2/models/pull/reward_curve_20250419_1725.png
  IEP2/models/pull/reward_curve_20250419_1726.png
  IEP2/models/push/ppo_push_model_20250419_1725.zip
  IEP2/models/push/ppo_push_model_20250419_1726.zip
  IEP2/models/push/ppo_push_model_latest.zip
  IEP2/models/push/reward_curve_20250419_1720.png
  IEP2/models/push/reward_curve_20250419_1723.png
  IEP2/models/push/reward_curve_20250419_1725.png
  IEP2/models/push/reward_curve_20250419_1726.png
  IEP2/requirements.txt
  IEP2/scripts/__pycache__/evaluate.cpython-38.pyc
  IEP2/scripts/__pycache__/train.cpython-38.pyc
  IEP2/scripts/__pycache__/train_initial.cpython-38.pyc
  IEP2/scripts/__pycache__/train_with_feedback.cpython-38.pyc
  IEP2/scripts/evaluate_models.py
  IEP2/scripts/simulate_feedback_data.py
  IEP2/scripts/train_initial.py
  IEP2/scripts/train_with_feedback.py
  docker-compose.yml
Labels: feature, backend

#18 feat: add Lucide icons and exercise GIFs for workout UI
  EEP/.env
  EEP/.streamlit/config.toml
  EEP/pages/WorkoutRecommender.py
  EEP/static/gifs/barbell_rows.gif
  EEP/static/gifs/bench_press.gif
  EEP/static/gifs/bicep_curls.gif
  EEP/static/gifs/bulgarian_split_squats.gif
  EEP/static/gifs/cable_face_pull.gif
  EEP/static/gifs/calf_raises.gif
  EEP/static/gifs/chin_ups.gif
  EEP/static/gifs/close_grip_push_ups.gif
  EEP/static/gifs/deadlifts.gif
  EEP/static/gifs/dumbbell-hammer-curl.gif
  EEP/static/gifs/dumbbell_chest_press.gif
  EEP/static/gifs/dumbbell_front_raises.gif
  EEP/static/gifs/dumbbell_rows.gif
  EEP/static/gifs/dumbbell_step_ups.gif
  EEP/static/gifs/glute_bridges.gif
  EEP/static/gifs/goblet_squats.gif
  EEP/static/gifs/hammer_curls.gif
  EEP/static/gifs/incline_dumbbell_press.gif
  EEP/static/gifs/incline_push_ups.gif
  EEP/static/gifs/inverted_rows.gif
  EEP/static/gifs/jump_squats.gif
  EEP/static/gifs/leg_extensions.gif
  EEP/static/gifs/leg_press.gif
  EEP/static/gifs/lunges.gif
  EEP/static/gifs/machine_chest_press.gif
  EEP/static/gifs/overhead_press.gif
  EEP/static/gifs/pull_ups.gif
  EEP/static/gifs/push_up_to_shoulder_tap.gif
  EEP/static/gifs/push_ups.gif
  EEP/static/gifs/renegade_rows.gif
  EEP/static/gifs/resistance_band_chest_press.gif
  EEP/static/gifs/resistance_band_rows.gif
  EEP/static/gifs/resistance_band_squats.gif
  EEP/static/gifs/seated_cable_rows.gif
  EEP/static/gifs/seated_leg_curl.gif
  EEP/static/gifs/split_squats.gif
  EEP/static/gifs/squats.gif
  EEP/static/gifs/triceps_dips.gif
  EEP/static/gifs/wall_push_ups.gif
  EEP/static/gifs/wall_sit.gif
  EEP/static/icons/biceps-flexed.svg
  EEP/static/icons/circle-check-big.svg
  EEP/static/icons/clock.svg
  EEP/static/icons/film.svg
  EEP/static/icons/gauge.svg
  EEP/static/icons/goal.svg
  EEP/static/icons/send.svg
  EEP/static/icons/star.svg
Labels: feature, frontend

#20 feat: Add new exercise GIFs and Lucide icons for improved UI visuals
  EEP/static/gifs/barbell_row.gif
  EEP/static/gifs/bicep_curl.gif
  EEP/static/gifs/bulgarian_split_squat.gif
  EEP/static/gifs/close_grip_push_up.gif
  EEP/static/gifs/deadlift.gif
  EEP/static/gifs/dumbbell_front_raise.gif
  EEP/static/gifs/dumbbell_row.gif
  EEP/static/gifs/dumbbell_step_up.gif
  EEP/static/gifs/glute_bridge.gif
  EEP/static/gifs/goblet_squat.gif
  EEP/static/gifs/hammer_curl.gif
  EEP/static/gifs/incline_push_up.gif
  EEP/static/gifs/inverted_row.gif
  EEP/static/gifs/jump_squat.gif
  EEP/static/gifs/leg_extension.gif
  EEP/static/gifs/lunge.gif
  EEP/static/gifs/pull_up.gif
  EEP/static/gifs/push_up.gif
  EEP/static/gifs/renegade_row.gif
  EEP/static/gifs/resistance_band_row.gif
  EEP/static/gifs/resistance_band_squat.gif
  EEP/static/gifs/seated_cable_row.gif
  EEP/static/gifs/split_squat.gif
  EEP/static/gifs/squat.gif
  EEP/static/gifs/tricep_dip.gif
  EEP/static/gifs/tricep_extension.webp
  EEP/static/gifs/wall_push_up.gif
  EEP/static/icons/circle-stop.svg
  EEP/static/icons/cpu.svg
  EEP/static/icons/rocket.svg
  EEP/static/icons/square-play.svg
  EEP/static/icons/triangle-alert.svg
  EEP/static/icons/upload.svg
  EEP/static/icons/video.svg
Labels: feature, frontend

#26 feat: modify iep3 url
  EEP/.env
  EEP/core/config.py
  EEP/pages/chatbot.py
Labels: feature, backend

#31 feat: support monitoring using grafana and prometheus
  IEP3/main.py
  IEP3/requirements.txt
  README.md
  docker-compose.yml
  prometheus.yml
Labels: feature

#32 chore: setup AKS deployment workflow with CI/CD pipeline
  .github/workflows/deploy-aks.yml
  EEP/requirements.txt
  IEP1/requirements.txt
  IEP2/requirements.txt
  k8s/eep-configmap.yaml
  k8s/eep-deployment.yaml
  k8s/eep-service.yaml
  k8s/iep1-deployment.yaml
  k8s/iep1-service.yaml
  k8s/iep2-deployment.yaml
  k8s/iep2-service.yaml
  k8s/iep3-deployment.yaml
  k8s/iep3-service.yaml
Labels: feature

#35 Merge develop to main
  IEP3/__init__.py
  IEP3/requirements.txt
  IEP3/tests/test_iep3.py
Labels: tests
